//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        public AspNetUsers()
        {
            this.bubble_groups = new HashSet<bubble_groups>();
            this.chat_members = new HashSet<chat_members>();
            this.event_users = new HashSet<event_users>();
            this.events = new HashSet<events>();
            this.friends_added = new HashSet<friends_added>();
            this.friends_added1 = new HashSet<friends_added>();
            this.post_likes = new HashSet<post_likes>();
            this.group_users = new HashSet<group_users>();
            this.like_comments = new HashSet<like_comments>();
            this.messages = new HashSet<messages>();
            this.post_comments = new HashSet<post_comments>();
            this.posts = new HashSet<posts>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public Nullable<bool> user_status { get; set; }
        public Nullable<int> FK_users_userrank { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string NickName { get; set; }
        public string UserName { get; set; }
        public string profile_image { get; set; }
    
        public virtual ICollection<bubble_groups> bubble_groups { get; set; }
        public virtual ICollection<chat_members> chat_members { get; set; }
        public virtual ICollection<event_users> event_users { get; set; }
        public virtual ICollection<events> events { get; set; }
        public virtual ICollection<friends_added> friends_added { get; set; }
        public virtual ICollection<friends_added> friends_added1 { get; set; }
        public virtual ICollection<post_likes> post_likes { get; set; }
        public virtual ICollection<group_users> group_users { get; set; }
        public virtual ICollection<like_comments> like_comments { get; set; }
        public virtual ICollection<messages> messages { get; set; }
        public virtual ICollection<post_comments> post_comments { get; set; }
        public virtual ICollection<posts> posts { get; set; }
        public virtual user_ranks user_ranks { get; set; }
    }
}
