//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class bubble_errors
    {
        public int C_ID { get; set; }
        public string error_owner { get; set; }
        public string error_msg { get; set; }
        public Nullable<System.DateTime> time_of_error { get; set; }
    }
}
