//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class bubble_groups
    {
        public bubble_groups()
        {
            this.group_users = new HashSet<group_users>();
            this.posts = new HashSet<posts>();
        }
    
        public int C_ID { get; set; }
        public string group_name { get; set; }
        public string group_description { get; set; }
        public string FK_bubble_groups_users { get; set; }
        public string group_profile_image { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<group_users> group_users { get; set; }
        public virtual ICollection<posts> posts { get; set; }
    }
}
