//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_members
    {
        public int C_ID { get; set; }
        public string FK_chat_members_user { get; set; }
        public int FK_chat_members_chat { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual chats chats { get; set; }
    }
}
