//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int C_ID { get; set; }
        public string message { get; set; }
        public string FK_messages_user { get; set; }
        public System.DateTime time_stamp { get; set; }
        public int FK_messages_chat_id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual chats chats { get; set; }
    }
}
