//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class posts
    {
        public posts()
        {
            this.post_comments = new HashSet<post_comments>();
            this.post_likes = new HashSet<post_likes>();
        }
    
        public int C_ID { get; set; }
        public string content_text { get; set; }
        public string content_picture { get; set; }
        public Nullable<System.DateTime> time_inserted { get; set; }
        public Nullable<int> FK_posts_bubble_groups { get; set; }
        public string FK_posts_users { get; set; }
        public Nullable<byte> content_is_video { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual bubble_groups bubble_groups { get; set; }
        public virtual ICollection<post_comments> post_comments { get; set; }
        public virtual ICollection<post_likes> post_likes { get; set; }
    }
}
