//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_comments
    {
        public post_comments()
        {
            this.like_comments = new HashSet<like_comments>();
        }
    
        public int C_ID { get; set; }
        public string comment { get; set; }
        public Nullable<int> FK_post_comments_posts { get; set; }
        public string FK_post_comments_users { get; set; }
        public Nullable<System.DateTime> comment_time { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ICollection<like_comments> like_comments { get; set; }
        public virtual posts posts { get; set; }
    }
}
