//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string C_ID { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public Nullable<byte> user_status { get; set; }
        public Nullable<int> FK_users_userrank { get; set; }
        public string profile_image { get; set; }
    }
}
