//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class chats
    {
        public chats()
        {
            this.chat_members = new HashSet<chat_members>();
            this.messages = new HashSet<messages>();
        }
    
        public int C_ID { get; set; }
        public string chat_name { get; set; }
    
        public virtual ICollection<chat_members> chat_members { get; set; }
        public virtual ICollection<messages> messages { get; set; }
    }
}
