//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class friends_added
    {
        public int C_ID { get; set; }
        public string FK_friends_added_users_Addee { get; set; }
        public string FK_friends_added_users_Added { get; set; }
        public Nullable<bool> friended { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
