//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class like_comments
    {
        public int C_ID { get; set; }
        public Nullable<int> FK_like_comments_post_comments { get; set; }
        public Nullable<bool> comment_like { get; set; }
        public Nullable<byte> comment_burst { get; set; }
        public string FK_like_comments_users { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual post_comments post_comments { get; set; }
    }
}
