//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bubblespace
{
    using System;
    using System.Collections.Generic;
    
    public partial class post_likes
    {
        public int C_ID { get; set; }
        public Nullable<int> FK_group_post_likes_group_posts { get; set; }
        public Nullable<byte> group_insert_like { get; set; }
        public Nullable<byte> insert_burst { get; set; }
        public string FK_group_post_like_users { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual posts posts { get; set; }
    }
}
